# Generated by Django 2.2.10 on 2020-02-18 15:12

import compare.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('problemInfo', models.TextField(verbose_name='Problem Details')),
                ('evaluationCode', models.TextField(verbose_name='Evaluation Code')),
                ('isValid', models.BooleanField(default=False, verbose_name='Valid?')),
                ('isReleased', models.BooleanField(default=False, verbose_name='Released?')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.AutoField(primary_key=True, serialize=False)),
                ('solutionCode', models.TextField(verbose_name='Submitted Solution')),
                ('isVerified', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataID', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='datasets/', validators=[compare.validators.validate_file])),
                ('datasetDesc', models.CharField(max_length=100, verbose_name='Dataset Short Description')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Problem')),
            ],
        ),
    ]
